### ISSUE TITLE
UndefVarError on imports when using @route

### ISSUE THREAD

**Issue by cerebralcourt** [neomatrixcode/Merly.jl#17]
**Describe the bug**
I get a "variable not defined" error from both the Redis and Formatting packages when using `@route GET "/url"` but not when using `Get("/url", (res, req))`. I prefer the @route syntax so it's slightly inconvenient for me.

**To Reproduce**
```julia
using Merly, Redis, Formatting

server = Merly.app()
conn = RedisConnection()

@route GET "/test-redis" begin
    res.body = Redis.get(conn, "key")
end

@route GET "/test-format" begin
    res.body = Formatting.format("Hello {:s}", "world")
end

server.start()
```

```bash
curl -v "http://localhost:8000/test-redis"
curl -v "http://localhost:8000/test-format"
```

**Expected behavior**
A GET route that can connect to a Redis database or format a string. Instead get "UndefVarError: Redis not defined". I also tested HTTP and JSON packages and they are both defined when using @route.

**Environment**
 - OS: Ubuntu and Fedora both do this

**Comment by codeneomatrix** [comment]
Good morning, thanks for the issue, excuse the question which version of Julia are you using?

**Comment by kogad** [comment]
Hi, I hava a same problem in v1.6 (macOS) with following code:

```julia
using Merly
using JSON

function tojson(data::String)
    return JSON.parse(data)
end

formats["application/json"] = tojson

# does not work
@route GET "/get/foo" begin
    println(json(request.body))
    HTTP.Response(200, "ok")
end

Get("/get/bar", (request, HTTP) -> begin
    println(json(request.body))
    HTTP.Response(200, "ok")
end)

start(host="127.0.0.1", port=8086, verbose=true)
```
I think this is an escaping or hygine problem, but I could not fix it.

**Comment by neomatrixcode** [comment]
In version 1.0, so that the function that processes the request can access existing functions or values ​​in the main program, you can write the following:

```
@route GET "/get/foo" (;tojson=tojson) begin
    println(json(request.body))
    HTTP.Response(200, "ok")
end
```

for more information you can consult the documentation
https://neomatrixcode.gitbook.io/merly/guide/routing


however if you just want to convert the body to json format, no action is required on your part, as you can read here:
https://neomatrixcode.gitbook.io/merly/guide/bodyparser

**Comment by kogad** [comment]
thank you, @neomatrixcode . it worked!
